// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: huang.proto

package huangclient

import (
	"context"
	huang2 "zero-basics/rpc/huang/huang"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = huang2.Request
	Response = huang2.Response

	Huang interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultHuang struct {
		cli zrpc.Client
	}
)

func NewHuang(cli zrpc.Client) Huang {
	return &defaultHuang{
		cli: cli,
	}
}

func (m *defaultHuang) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := huang2.NewHuangClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
