// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: huang.proto

package huang

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Huang_Ping_FullMethodName = "/huang.Huang/Ping"
)

// HuangClient is the client API for Huang service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HuangClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type huangClient struct {
	cc grpc.ClientConnInterface
}

func NewHuangClient(cc grpc.ClientConnInterface) HuangClient {
	return &huangClient{cc}
}

func (c *huangClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Huang_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HuangServer is the server API for Huang service.
// All implementations must embed UnimplementedHuangServer
// for forward compatibility.
type HuangServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedHuangServer()
}

// UnimplementedHuangServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHuangServer struct{}

func (UnimplementedHuangServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedHuangServer) mustEmbedUnimplementedHuangServer() {}
func (UnimplementedHuangServer) testEmbeddedByValue()               {}

// UnsafeHuangServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HuangServer will
// result in compilation errors.
type UnsafeHuangServer interface {
	mustEmbedUnimplementedHuangServer()
}

func RegisterHuangServer(s grpc.ServiceRegistrar, srv HuangServer) {
	// If the following call pancis, it indicates UnimplementedHuangServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Huang_ServiceDesc, srv)
}

func _Huang_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HuangServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Huang_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HuangServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Huang_ServiceDesc is the grpc.ServiceDesc for Huang service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Huang_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "huang.Huang",
	HandlerType: (*HuangServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Huang_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "huang.proto",
}
