// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: huang.proto

package server

import (
	"context"
	huang2 "zero-basics/rpc/huang/huang"
	"zero-basics/rpc/huang/internal/logic"
	"zero-basics/rpc/huang/internal/svc"
)

type HuangServer struct {
	svcCtx *svc.ServiceContext
	huang2.UnimplementedHuangServer
}

func NewHuangServer(svcCtx *svc.ServiceContext) *HuangServer {
	return &HuangServer{
		svcCtx: svcCtx,
	}
}

func (s *HuangServer) Ping(ctx context.Context, in *huang2.Request) (*huang2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
